# Generated by Django 5.2.7 on 2025-10-25 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='My_projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Título do Projeto')),
                ('image_porject', models.ImageField(blank=True, null=True, upload_to='projetos/')),
                ('summary', models.CharField(verbose_name='Resumo Projeto')),
                ('year', models.PositiveBigIntegerField(verbose_name='Ano do Projeto')),
                ('link_github', models.URLField(verbose_name='Link do Reposistório no GitHub')),
            ],
            options={
                'verbose_name': 'Projecto',
                'verbose_name_plural': 'Projectos',
                'ordering': ['-year'],
            },
        ),
    ]
