# Generated by Django 5.2.7 on 2025-10-28 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_portifolio_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyActivities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_activ', models.CharField(max_length=100, verbose_name='Título da atividade')),
                ('summary_activ', models.CharField(max_length=250, verbose_name='Resumo sobre atividade')),
                ('year_activ', models.PositiveBigIntegerField(verbose_name='Ano da atividade')),
                ('image_activ', models.ImageField(blank=True, null=True, upload_to='projetos/')),
            ],
            options={
                'verbose_name': 'Activitie',
                'verbose_name_plural': 'My Activities',
                'ordering': ['-year_activ'],
            },
        ),
        migrations.RenameModel(
            old_name='My_projects',
            new_name='MyProjects',
        ),
        migrations.AlterModelOptions(
            name='myprojects',
            options={'ordering': ['-year_project'], 'verbose_name': 'Projecto', 'verbose_name_plural': 'Projectos'},
        ),
        migrations.RenameField(
            model_name='myprojects',
            old_name='title',
            new_name='title_project',
        ),
        migrations.RenameField(
            model_name='myprojects',
            old_name='year',
            new_name='year_project',
        ),
    ]
