# Generated by Django 5.2.7 on 2025-11-02 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_portifolio_app', '0002_myactivities_rename_my_projects_myprojects_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyGraduations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_greduation', models.CharField(max_length=400, verbose_name='Nome da graduação')),
                ('name_institution', models.CharField(max_length=200, verbose_name='Nome da instituição')),
                ('description', models.CharField(max_length=1000, verbose_name='Sobre a graduação')),
                ('year_start_graduation', models.PositiveBigIntegerField(verbose_name='Ano de inicio')),
                ('year_end_graduation', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Ano de conclusão')),
            ],
            options={
                'verbose_name': 'Graduations',
                'verbose_name_plural': 'Graduation',
                'ordering': ['-year_start_graduation'],
            },
        ),
        migrations.AlterField(
            model_name='myactivities',
            name='image_activ',
            field=models.ImageField(blank=True, null=True, upload_to='activities/'),
        ),
    ]
